#!/bin/bash

# Update and upgrade the system
sudo pacman -Syu

# Xorg display server installation
sudo pacman -S xorg-server xorg-xinit xorg-xinput

# INCLUDES make,etc.
sudo pacman -S base-devel python-pip

# Microcode for Intel/AMD 
sudo pacman -S intel-ucode

# Network Manager
sudo pacman -S networkmanager network-manager-applet

# Installation for Appearance management
sudo pacman -S lxappearance

# File Manager (eg. pcmanfm, krusader, thunar)
sudo pacman -S thunar

# Network File Tools/System Events
sudo pacman -S dialog mtools dosfstools avahi acpi acpid gvfs xfce4-power-manager

sudo systemctl enable avahi-daemon
sudo systemctl enable acpid

# Terminal (eg. terminator, kitty)
sudo pacman -S xfce4-terminal

# Sound packages
sudo pacman -S pulseaudio alsa-utils pavucontrol volumeicon

# Neofetch/HTOP
sudo pacman -S neofetch htop

# EXA installation
# replace ls command in .bashrc file with line below
# alias ls='exa -al --long --header --color=always --group-directories-first' 
sudo pacman -S exa

# Printing and bluetooth (if needed)
# sudo pacman -S cups
# sudo pacman -S bluez bluez-utils blueman

# sudo systemctl enable bluetooth
# sudo systemctl enable cups

# Browser Installation (eg. chromium)
sudo pacman -S firefox

# Desktop background browser/handler 
# feh --bg-fill /path/to/directory 
# example if you want to use in autostart located in ~/.config/qtile/autostart.sh
sudo pacman -S feh
# sudo pacman -S nitrogen

# Packages needed qtile after installation
sudo pacman -S picom dunst sxhkd rofi libnotify unzip scrot geany geany-plugins

# Command line text editor -- nano preinstalled  -- I like micro but vim is great
sudo pacman -S micro
# sudo pacman -S neovim

# Install fonts and papirus icon theme and arc-theme
sudo pacman -S ttf-font-awesome ttf-ubuntu-font-family ttf-liberation terminus-font papirus-icon-theme arc-gtk-theme

# Configure Spanish keyboard layout
sudo localectl set-x11-keymap es

# Disable lightdm
sudo systemctl disable lightdm.service

# Enable lightdm
# sudo systemctl enable lightdm.service

# Restart system
# sudo systemctl reboot

# Install Qtile dependencies
sudo pacman -S dbus-python python-xcffib python-cairocffi python-psutil

# Install Qtile from GitHub
cd
git clone https://github.com/qtile/qtile
cd qtile
pip3 install .

# Add .xinitrc
echo 'exec qtile' > ~/.xinitrc

# Enable lightdm
sudo systemctl enable lightdm.service

# Restart system
sudo systemctl reboot
