#!/bin/bash

# Advertencia al usuario
echo "Este script configurará LightDM y el archivo de inicio de sesión lightdm.conf. Continuar? (y/n)"
read answer
if [ "$answer" != "y" ]; then
    echo "Abortando configuración."
    exit 1
fi

# Definir variables
DM_PACKAGES="lightdm lightdm-gtk-greeter"

# Instalar paquetes de LightDM
echo "Instalando paquetes de LightDM..."
sudo pacman -S $DM_PACKAGES

# Configurar archivo de inicio de sesión lightdm.conf
echo "Configurando archivo de inicio de sesión lightdm.conf..."
sudo nano /etc/lightdm/lightdm.conf

echo "Asegúrate de cambiar 'example' a 'lightdm' en 'greeter-session' y también 'gnome' a 'greeter'."

# Habilitar servicio de inicio de sesión
echo "Habilitando servicio de inicio de sesión..."
sudo systemctl enable lightdm.service

# Mensaje final
echo "La configuración de LightDM ha finalizado correctamente. Recuerda verificar el archivo /etc/lightdm/lightdm.conf para asegurarte de que los cambios se hayan aplicado correctamente."
