#!/bin/bash

sudo pacman -S lightdm lightdm-gtk-greeter

sudo pacman -S qtile xterm code firefox rofi which nitrogen

sudo pacman -S ttf-dejavu ttf-liberation noto-fonts

sudo pacman -S pulseaudio pavucontrol pamixer

sudo pacman -S arandr udiskie ntfs-3g network-manager-applet

sudo pacman -S volumeicon cbtticon xorg-xinit base-devel git thunar ranger glib2 gvfs lxappearance picom geeqie vlc

echo "Ahora que tienes todo instalado configura el siguiente archivo"
sudo nano /etc/lightdm/lightdm.conf
echo "Comprueba que hayas cambiado de exampla a light en greeter-session y tambien de gnome a greeter"

systemctl enable lightdm.service
